# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# Force Gradle to use Android Studio JBR to avoid VS Code JRE conflict
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.java.installations.paths=C\:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.java.installations.auto-detect=false
